config/routes.rb
SampleApp::Application.routes.draw do
  get "sessions/new"

  root :to => 'pages#home'

  match '/contact', :to => 'pages#contact'
  match '/about', :to => 'pages#about'
  match '/help', :to => 'pages#help'
  match '/signup', :to => 'users#new'
  match '/signin', :to => 'sessions#new'
  match '/signout', :to => 'sessions#destroy'
  
  resources :users do
    member do
      get :following, :followers
    end
  end

  resources :sessions, :only => [:new, :create, :destroy]
  resources :microposts, :only => [:create, :destroy]
  resources :relationships, :only => [:create, :destroy]

end

app/views/layouts/_error_messages.html.erb
<% if object.errors.any? %>
  <div class="error_explanation">
    <h5><%= pluralize(object.errors.count, "error") %> prohibited this <%= object.class.to_s.underscore.humanize.downcase %> from being saved.</h5>
    <p>The following errors occured:</p>
    <ul>
    <% object.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_feed.html.erb
<% if @feed_items.any? %>
<ul class="microposts">
  <%= render :partial => 'layouts/feed_item', :collection => @feed_items %>
</ul>
<%= will_paginate @feed_items %>
<% end %>

app/views/layouts/_feed_item.html.erb
<li>
  <%= link_to gravatar_for(feed_item.user), feed_item.user %>
  <p class="user"><%= link_to feed_item.user.name, feed_item.user %>
  <p class="content"><%= feed_item.content %></p>
  <p class="timestamp">Posted <%= time_ago_in_words(feed_item.created_at)%> ago.</p>
  <% if current_user?(feed_item.user) %>
  <%= link_to "delete", feed_item, :method => :delete, :confirm => "Are you sure?", :title => feed_item.content %>
  <% end %>
</li>

app/views/layouts/_micropost_form.html.erb
<%= form_for(@micropost) do |f| %>
  <%= render 'layouts/error_messages', :object => f.object %>
  <%= f.text_area :content %>
  <%= f.submit "Submit" %>
<% end %>

app/views/layouts/_user_info.html.erb
<section class="profile">
  <%= link_to gravatar_for(current_user, :size => 75), current_user %>
  <ul>
    <li class="name">Name: <strong><%= current_user.name %></strong></li>
    <li class="link">URL: <strong><%= link_to user_path(current_user), user_path(current_user) %></strong></li>
    <li class="count"><%= pluralize(current_user.microposts.count, "post") %></li>
    <% @user ||= current_user %>
    <li class="following"><a href="<%= following_user_path(@user) %>">Following <%= pluralize(@user.following.count, "user") %></a></li>
    <li class="followers"><a href="<%= followers_user_path(@user) %>">Followed by <%= pluralize(@user.followers.count, "user") %></a></li>
  </ul>
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
    <title><%= title %></title>
    <!--[if lt IE 9]>
    <script src="//html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->
    <%= stylesheet_link_tag :all %>
    <%= javascript_include_tag :defaults %>
    <%= csrf_meta_tag %>
</head>
<body>
<header>
    <h1><%= link_to "Retreet", root_path %></h1>
    <nav>
        <ul>
            <li><%= link_to "Home", root_path %></li>
            <% if signed_in? %>
            <li><%= link_to "Profile", current_user %></li>
            <li><%= link_to "Users", users_path %></li>
            <li><%= link_to "Settings", edit_user_path(current_user) %></li>
            <% end %>
            <li><%= link_to "Help", help_path %></li>
            <% if signed_in? %>
            <li><%= link_to "Sign out", signout_path %></li>
            <% else %>
            <li><%= link_to "Sign in", signin_path %></li>
            <% end %>
        </ul>
    </nav>
</header>
<section class="content">
<% flash.each do |key, value| %>
  <h5 class="flash <%= key %>"><%= value %></h5>
<% end %>
<%= yield %>
</section>
<footer>
    <nav>
        <ul>
            <li><%= link_to "About", about_path %></li>
            <li><%= link_to "Contact", contact_path %></li>
            <li><%= link_to "The Columbian", 'http://www.columbian.com' %></li>
        </ul>
    </nav>
</footer>
<%= debug(params) if Rails.env.development? %>
</body>
</html>